

MESSAGE( STATUS "CPPTEST_INCLUDE_DIRS " ${CPPTEST_INCLUDE_DIRS} )
MESSAGE( STATUS "CPPTEST_LIBRARIES " ${CPPTEST_LIBRARIES} )

MESSAGE( STATUS "LIBXML2_INCLUDE_DIR " ${LIBXML2_INCLUDE_DIR} )
MESSAGE( STATUS "LIBXML2_LIBRARIES " ${LIBXML2_LIBRARIES} )

MESSAGE( STATUS "FLTK_INCLUDE_DIR " ${FLTK_INCLUDE_DIR} )
MESSAGE( STATUS "FLTK_LIBRARIES " ${FLTK_LIBRARIES} )

MESSAGE( STATUS "JPEG_INCLUDE_DIR " ${JPEG_INCLUDE_DIR} )
MESSAGE( STATUS "JPEG_LIBRARIES " ${JPEG_LIBRARIES} )

MESSAGE(STATUS "GLM_INCLUDE_DIR = ${GLM_INCLUDE_DIR}")

MESSAGE( STATUS "GLEW_INCLUDE_PATH " ${GLEW_INCLUDE_PATH})
MESSAGE( STATUS "GLEW_LIBRARY " ${GLEW_LIBRARY})

MESSAGE( STATUS "EIGEN3_INCLUDE_DIR = ${EIGEN3_INCLUDE_DIR}")

MESSAGE( STATUS "CodeEli_INCLUDE_DIRS = ${CodeEli_INCLUDE_DIRS}")

MESSAGE( STATUS "CMINPACK_INCLUDE_DIR " ${CMINPACK_INCLUDE_DIR})
MESSAGE( STATUS "CMINPACK_LIBRARIES " ${CMINPACK_LIBRARIES})

MESSAGE( STATUS "STEPCODE_INCLUDE_DIR " ${STEPCODE_INCLUDE_DIR})
MESSAGE( STATUS "STEPCODE_LIBRARIES " ${STEPCODE_LIBRARIES})

MESSAGE( STATUS "LIBIGES_LIBRARIES: " ${LIBIGES_LIBRARIES} )
MESSAGE( STATUS "LIBIGES_INCLUDE_DIR: " ${LIBIGES_INCLUDE_DIR} )
