#!/bin/bash
set -e;
echo "Setting up symlinks ...";
ln -nsf /opt/OpenVSP/vsp /usr/local/bin/vsp;
ln -nsf /opt/OpenVSP/vspaero /usr/local/bin/vspaero;
ln -nsf /opt/OpenVSP/vspscript /usr/local/bin/vspscript;
ln -nsf /opt/OpenVSP/vspslicer /usr/local/bin/vspslicer;
ln -nsf /opt/OpenVSP/vspviewer /usr/local/bin/vspviewer;
