ExternalProject_Add( EIGEN
	URL ${CMAKE_SOURCE_DIR}/eigen-eigen-1f4c0311cda3.tar.gz
	DOWNLOAD_EXTRACT_TIMESTAMP TRUE
	UPDATE_COMMAND ""
	BUILD_COMMAND ""
	CMAKE_ARGS
		-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
		-DCMAKE_BUILD_TYPE=Release
)
ExternalProject_Get_Property( EIGEN INSTALL_DIR )
SET( EIGEN_INSTALL_DIR ${INSTALL_DIR} )
