# An external project for libxml2 https://gitlab.gnome.org/GNOME/libxml2
#
# Static library only, without iconv, zlib, ICU, or dynamic modules.  The
# installed CMake package (libxml2-config.cmake) provides the link
# dependencies and LIBXML_STATIC definition consumers need.

ExternalProject_Add( LIBXML2
	URL ${CMAKE_SOURCE_DIR}/libxml2-2.15.4.tar.xz
	DOWNLOAD_EXTRACT_TIMESTAMP TRUE
	CMAKE_ARGS -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
		-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
		-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
		-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
		-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
		-DCMAKE_INSTALL_LIBDIR=lib
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-DBUILD_SHARED_LIBS=OFF
		-DLIBXML2_WITH_ICONV=OFF
		-DLIBXML2_WITH_ZLIB=OFF
		-DLIBXML2_WITH_ICU=OFF
		-DLIBXML2_WITH_MODULES=OFF
		-DLIBXML2_WITH_PYTHON=OFF
		-DLIBXML2_WITH_PROGRAMS=OFF
		-DLIBXML2_WITH_TESTS=OFF
)
ExternalProject_Get_Property( LIBXML2 INSTALL_DIR )
SET( LIBXML2_INSTALL_DIR ${INSTALL_DIR} )
