
# Build STEPCode static libraries only, with the AP203 schema.
#
# Static libraries are named <lib>-static.  FindSTEPCODE.cmake must list
# the same libraries.

SET( STEPCODE_INSTALL_DIR ${CMAKE_BINARY_DIR}/STEPCODE-prefix )

SET( STEPCODE_BYPRODUCTS )
FOREACH( SC_LIB sdai_ap203 stepeditor stepcore stepdai steputils )
	LIST( APPEND STEPCODE_BYPRODUCTS
		${STEPCODE_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}${SC_LIB}-static${CMAKE_STATIC_LIBRARY_SUFFIX} )
ENDFOREACH()

ExternalProject_Add( STEPCODE
	URL ${CMAKE_CURRENT_SOURCE_DIR}/stepcode-4897d6118a9b.zip
	DOWNLOAD_EXTRACT_TIMESTAMP TRUE
	INSTALL_DIR ${STEPCODE_INSTALL_DIR}
	CMAKE_ARGS -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
		-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
		-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
		-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
		-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-DCMAKE_POSITION_INDEPENDENT_CODE=ON
		-DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
		-DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
		-DSC_BUILD_SCHEMAS=ap203/ap203.exp
		-DBUILD_SHARED_LIBS=OFF
		-DBUILD_STATIC_LIBS=ON
		-DSC_PYTHON_GENERATOR=OFF
		-DSC_ENABLE_TESTING=OFF
	BUILD_BYPRODUCTS ${STEPCODE_BYPRODUCTS}
)
