ExternalProject_Add( FLTK

	URL ${CMAKE_SOURCE_DIR}/fltk-ffe39737e53a.zip
	DOWNLOAD_EXTRACT_TIMESTAMP TRUE
	CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
		-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
		-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
		-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
		-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-DFLTK_BUILD_TEST:BOOL=OFF
		-DFLTK_USE_SYSTEM_LIBJPEG:BOOL=OFF
		-DFLTK_USE_SYSTEM_ZLIB:BOOL=OFF
		-DFLTK_USE_SYSTEM_LIBPNG:BOOL=OFF
)
ExternalProject_Get_Property( FLTK INSTALL_DIR )
SET( FLTK_INSTALL_DIR ${INSTALL_DIR} )
