ExternalProject_Add( OPENABF
	URL ${CMAKE_CURRENT_SOURCE_DIR}/OpenABF-ed546ea85410.zip
	DOWNLOAD_EXTRACT_TIMESTAMP TRUE
	CMAKE_ARGS -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
		-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
		-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
		-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
		-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-DBUILD_SHARED_LIBS=OFF
)
ExternalProject_Get_Property( OPENABF INSTALL_DIR )
SET( OPENABF_INSTALL_DIR ${INSTALL_DIR} )
