ExternalProject_Add( CODEELI
	URL ${CMAKE_SOURCE_DIR}/Code-Eli-a7a90d6903df.zip
	BUILD_COMMAND ""
	INSTALL_COMMAND ""
)
ExternalProject_Get_Property( CODEELI BINARY_DIR SOURCE_DIR )
SET( CODEELI_INSTALL_DIR ${BINARY_DIR} ${SOURCE_DIR})