ExternalProject_Add( CLIPPER2
	URL ${CMAKE_CURRENT_SOURCE_DIR}/Clipper2-20bd69475f48.zip
	DOWNLOAD_EXTRACT_TIMESTAMP TRUE
	SOURCE_SUBDIR "CPP"
	CMAKE_ARGS -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
		-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
		-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
		-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
		-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-DBUILD_SHARED_LIBS=OFF
		-DCLIPPER2_UTILS=OFF
		-DCLIPPER2_EXAMPLES=OFF
		-DCLIPPER2_TESTS=OFF
		-DCLIPPER2_USINGZ=OFF
)
ExternalProject_Get_Property( CLIPPER2 INSTALL_DIR )
SET( CLIPPER2_INSTALL_DIR ${INSTALL_DIR} )
