SET(SC_CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
SET(SC_CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")

IF(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "amd64")
	SET(SC_CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
	SET(SC_CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
ENDIF()

ExternalProject_Add( STEPCODE
    URL ${CMAKE_CURRENT_SOURCE_DIR}/stepcode-74b6fe4.zip
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
    INSTALL_DIR ${CMAKE_BINARY_DIR}
    CMAKE_ARGS -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DCMAKE_CXX_FLAGS=${SC_CMAKE_CXX_FLAGS}
        -DCMAKE_C_FLAGS=${SC_CMAKE_C_FLAGS}
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DSC_BUILD_SCHEMAS=ap203/ap203.exp
        -DBUILD_STATIC_LIBS=ON
        -DSC_BUILD_STATIC_LIBS=ON
        -DSC_PYTHON_GENERATOR=OFF
        -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
)
ExternalProject_Get_Property( STEPCODE SOURCE_DIR )
ExternalProject_Get_Property( STEPCODE BINARY_DIR )
ExternalProject_Get_Property( STEPCODE INSTALL_DIR )


SET( STEPCODE_INSTALL_DIR ${INSTALL_DIR} )
SET( STEPCODE_BINARY_DIR ${BINARY_DIR} )
