ExternalProject_Add( EIGEN
	URL ${CMAKE_SOURCE_DIR}/eigen-eigen-1f4c0311cda3.tar.gz
	DOWNLOAD_EXTRACT_TIMESTAMP TRUE
	UPDATE_COMMAND ""
	CONFIGURE_COMMAND ""
	BUILD_COMMAND ""
	INSTALL_COMMAND ""
)
ExternalProject_Get_Property( EIGEN SOURCE_DIR )
SET( EIGEN_INSTALL_DIR ${SOURCE_DIR} )