//
// This file is released under the terms of the NASA Open Source Agreement (NOSA)
// version 1.3 as detailed in the LICENSE file which accompanies this software.
//
//////////////////////////////////////////////////////////////////////

#ifndef SURFIDNUMS
#define SURFIDNUMS

// Surface ID numbers

#define BODY               1010
#define WING               1020
#define BODYBASE           1030
#define INLETRAMP          9000
#define NOZZLE            10000
#define COWL              11000

#endif

